name: C++ CI with Make

on:
  push:
    branches: [branchHTTPservVertical]
  pull_request:
    branches: [branchHTTPservVertical]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: |
          autoreconf --install

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfile image for amd64
        run: docker build --platform=linux/amd64 -t rpjc/optimaserver:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker build --platform=linux/arm64 -t rpjc/optimaserver:arm64 --push .

      - name: Create manifest
        run: docker manifest create rpjc/optimaserver --amend rpjc/optimaserver:amd64 --amend rpjc/optimaserver:arm64

      - name: Push manifest to docker hub
        run: docker manifest push rpjc/optimaserver