name: C++ CI with Make

on:
  push:
    branches: [branchAutomake]
  pull_request:
    branches: [branchAutomake]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++

      - name: Generate configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      

      - name: Build
        run: make

      - name: Create distribution
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: funca-dist
          path: funca-*.tar.gz
